runtime: python311
entrypoint: gunicorn -b :$PORT wsgi:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "sistemas-predictivo-lesiones"
  BUCKET_NAME: "flaskapp-resources"
  CLOUD_SQL_NAME: "postgresql"
  CLOUD_SQL_USERNAME: "rocio"
  CLOUD_SQL_DATABASE_NAME: "userdb"
  CLOUD_SQL_PASSWORD: "rocio9396"
  CLOUD_SQL_CONNECTION_NAME: "sistemas-predictivo-lesiones:europe-west1:postgresql"
  CLOUD_SQL_HOST: "34.38.196.5:5432"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  
handlers:
- url: /static
  static_dir: myapp/static
- url: /.*
  script: auto