version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - SPARK_HOME=/opt/spark-3.0.1-bin-hadoop2.7
    depends_on:
      - spark-master
    command: ["python", "app.py"]

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop2.7
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bde2020/spark-worker:3.0.1-hadoop2.7
    container_name: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    depends_on:
      - spark-master
