from myapp.extensions import db

class User(db.Model):
    __tablename__ = 'usuarios'

    id = db.Column(db.Integer, primary_key=True)
    edad = db.Column(db.Float)
    sexo = db.Column(db.Float)
    altura = db.Column(db.Float)
    peso = db.Column(db.Float)
    num_calzado = db.Column(db.Float)
    articulacion = db.Column(db.String(50))
    localizacion = db.Column(db.String(50))
    lado = db.Column(db.String(10))
    pace_walk = db.Column(db.Float)
    velocidad_walk = db.Column(db.Float)
    step_rate_walk = db.Column(db.Float)
    stride_length_walk = db.Column(db.Float)
    shock_walk = db.Column(db.Float)
    impact_gs_walk = db.Column(db.Float)
    braking_gs_walk = db.Column(db.Float)
    footstrike_type_walk = db.Column(db.Float)
    pronation_excursion_walk = db.Column(db.Float)
    contact_ratio_walk = db.Column(db.Float)
    total_force_rate_walk = db.Column(db.Float)
    step_length_walk = db.Column(db.Float)
    pronation_excursion_mp_to_walk = db.Column(db.Float)
    stance_excursion_fs_mp_walk = db.Column(db.Float)
    stance_excursion_mp_to_walk = db.Column(db.Float)
    m1_hipermovil = db.Column(db.Float)
    thomas_psoas = db.Column(db.Float)
    thomas_rf = db.Column(db.Float)
    thomas_tfl = db.Column(db.Float)
    ober = db.Column(db.Float)
    arco_aplanado = db.Column(db.Float)
    arco_elevado = db.Column(db.Float)
    m1_dfx = db.Column(db.Float)
    m5_hipermovil = db.Column(db.Float)
    arco_transverso_disminuido = db.Column(db.Float)
    m1_pfx = db.Column(db.Float)
    arco_transverso_aumentado = db.Column(db.Float)
    hlf = db.Column(db.Float)
    hl = db.Column(db.Float)
    hr = db.Column(db.Float)
    hav = db.Column(db.Float)
    index_minus = db.Column(db.Float)
    tfi = db.Column(db.Float)
    tfe = db.Column(db.Float)
    tti = db.Column(db.Float)
    tte = db.Column(db.Float)
    ober_friccion = db.Column(db.Float)
    popliteo = db.Column(db.Float)
    t_hintermann = db.Column(db.Float)
    jack_normal = db.Column(db.Float)
    jack_no_reconstruye = db.Column(db.Float)
    pronacion_no_disponible = db.Column(db.Float)
    heel_raise_double = db.Column(db.Float)
    heel_raise = db.Column(db.Float)
    fpi_total_i = db.Column(db.Float)
    fpi_total_d = db.Column(db.Float)
    tibia_vara_proximal = db.Column(db.Float)
    tibia_vara_distal = db.Column(db.Float)
    rotula_divergente = db.Column(db.Float)
    rotula_convergente = db.Column(db.Float)
    rotula_ascendida = db.Column(db.Float)
    genu_valgo = db.Column(db.Float)
    genu_varo = db.Column(db.Float)
    genu_recurvatum = db.Column(db.Float)
    genu_flexum = db.Column(db.Float)
    lunge = db.Column(db.Float)
    imc = db.Column(db.Float)
    zona_afectada = db.Column(db.String(100))

    def __repr__(self):
        return '<Usuario %r>' % self.id
